tsramol/Tsr.Web/Controllers/MasterDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Tsr.Core.Entities;
using Tsr.Core.Models;
using Tsr.Infra;
using Tsr.Web.Common;

namespace Tsr.Web.Controllers
{
    public class MasterDetailsController : Controller
    {
        AppContext db = new AppContext();

        public ActionResult Index()
        {
            return View();
        }

        #region Common
        public ActionResult FillCourse(int CategoryId)
        {
            var Courses = db.Courses.Where(c => c.CategoryId == CategoryId && c.IsActive == true);
            return Json(Courses, JsonRequestBehavior.AllowGet);
        }

        public JsonResult FillCourseForCourseFee(int CategoryId)
        {
            //var Courses = db.Courses.Where(c => c.CategoryId == CategoryId && c.IsActive == true);
            var Courses = from c in db.Courses
                    join cf in db.CourseFees on c.CourseId equals cf.CourseId
                    into ccf
                    from cf in ccf.DefaultIfEmpty()
                    where (cf == null && c.CategoryId == CategoryId && c.IsActive == true)
                    select new { c.CourseId, c.CourseName};
            return Json(Courses, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Organisation
        public async Task<ActionResult> OrganisationList()
        {
            return View(await db.Organisations.ToListAsync());
        }

        public ActionResult OrganisationCreate()
        {
            return PartialView("OrganisationCreate");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> OrganisationCreate(OrganisationMaster org)
        {
            if (ModelState.IsValid)
            {
                db.Organisations.Add(org);
                await db.SaveChangesAsync();
                return Json(new { success = true });
            }

            return PartialView("OrganisationCreate", org);
        }

        public async Task<ActionResult> OrganisationEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrganisationMaster fp = await db.Organisations.FindAsync(id);
            if (fp == null)
            {
                return HttpNotFound();
            }
            return PartialView("OrganisationEdit", fp);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> OrganisationEdit(OrganisationMaster obj)
        {
            if (ModelState.IsValid)
            {
                db.Entry(obj).State = EntityState.Modified;
                try
                {
                    await db.SaveChangesAsync();
                }
                catch (Exception e)
                {
                    string s = e.ToString();
                }
                return Json(new { success = true });
            }
            return PartialView("OrganisationEdit", obj);
        }

        #endregion

        #region FeesPattern
        public async Task<ActionResult> FeesPatternList()
        {
            return View(await db.FeesPatterns.ToListAsync());
        }

        public ActionResult FeesPatternCreate()
        {
            return PartialView("FeesPatternCreate");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> FeesPatternCreate(FeesPattern obj)
        {
            if (ModelState.IsValid)
            {
                db.FeesPatterns.Add(obj);
                await db.SaveChangesAsync();
                return Json(new { success = true });
            }

            return PartialView("FeesPatternCreate", obj);
        }

        public async Task<ActionResult> FeesPatternEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FeesPattern fp = await db.FeesPatterns.FindAsync(id);
            if (fp == null)
            {
                return HttpNotFound();
            }
            return PartialView("FeesPatternEdit", fp);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> FeesPatternEdit(FeesPattern obj)
        {
            if (ModelState.IsValid)
            {
                db.Entry(obj).State = EntityState.Modified;
                try
                {
                    await db.SaveChangesAsync();
                }
                catch (Exception e)
                {
                    string s = e.ToString();
                }
                return Json(new { success = true });
            }
            return PartialView("FeesPatternEdit", obj);
        }

        public async Task<ActionResult> FeesPatternDeactive( int? id, string flag = null)
        {
            
            if (id == null)
            {
                 return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FeesPattern fp = await db.FeesPatterns.FindAsync(id);

            if (fp == null)
            {
                return HttpNotFound();
            }
            if (flag == "D")
                fp.IsActive = false;
            if (flag == "A")
                fp.IsActive = true;

            db.SaveChanges();
            return RedirectToAction("FeesPatternList");
        }

        #endregion

        #region Employee
        public async Task<ActionResult> EmployeeList()
        {
            
            var vm = from e in db.Employees
                     join d in db.Designations on e.DesignationId equals d.DesignationId
                     select new MasterEmployeeListVM { Emp = e, Desig = d };

            return View(await vm.ToListAsync());
        }

        public ActionResult EmployeeCreate()
        {
            ViewBag.Designations = new SelectList(db.Designations.ToList(),"DesignationId", "DesignationName");
            ViewBag.Organisations = new SelectList(db.Organisations.ToList(), "OrganisationId", "Name");
            return PartialView("EmployeeCreate");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EmployeeCreate(Employee obj)
        {
            if (ModelState.IsValid)
            {
                db.Employees.Add(obj);
                await db.SaveChangesAsync();
                return Json(new { success = true });
            }
            ViewBag.Designations = new SelectList(db.Designations.ToList(), "DesignationId", "DesignationName");
            ViewBag.Organisations = new SelectList(db.Organisations.ToList(), "OrganisationId", "Name");
            return PartialView("EmployeeCreate", obj);
        }

        public async Task<ActionResult> EmployeeEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee em = await db.Employees.FindAsync(id);
            if (em == null)
            {
                return HttpNotFound();
            }
            ViewBag.Designations = new SelectList(db.Designations.ToList(), "DesignationId", "DesignationName");
            ViewBag.Organisations = new SelectList(db.Organisations.ToList(), "OrganisationId", "Name");
            return PartialView("EmployeeEdit", em);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EmployeeEdit(Employee obj)
        {
            if (ModelState.IsValid)
            {
                db.Entry(obj).State = EntityState.Modified;
                try
                {
                    await db.SaveChangesAsync();
                }
                catch (Exception e)
                {
                    string s = e.ToString();
                }
                return Json(new { success = true });
            }
            return PartialView("EmployeeEdit", obj);
        }

        public async Task<ActionResult> EmployeeDeactive(int? id, string flag = null)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee fp = await db.Employees.FindAsync(id);

            if (fp == null)
            {
                return HttpNotFound();
            }
            if (flag == "D")
                fp.IsActive = false;
            if (flag == "A")
                fp.IsActive = true;

            db.SaveChanges();
            return RedirectToAction("EmployeeList");
        }

        public async Task<ActionResult> EmployeeDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee em = await db.Employees.FindAsync(id);
            if (em == null)
            {
                return HttpNotFound();
            }
            ViewBag.Designations = new SelectList(db.Designations.ToList(), "DesignationId", "DesignationName");
            ViewBag.Organisations = new SelectList(db.Organisations.ToList(), "OrganisationId", "Name");
            return PartialView("EmployeeDetails", em);
        }

        #endregion

        #region Department
        public async Task<ActionResult> DepartmentList()
        {
            var obj = from d in db.Departments
                      join e in db.Employees
                      on d.DepartmentHead equals e.EmployeeId
                      select new MasterDetpartmentListVM
                      {
                          DepartmentId = d.DepartmentId,
                          DepartmentName = d.Name,
                          Address = d.Address,
                          Phone = d.Phone,
                          Extension = d.PhoneExtension,

tsramol/Tsr.Web/Views/MasterDetails/BatchList.cshtml
@model IEnumerable<Tsr.Core.Models.BatchListVM>

@{
    ViewBag.Title = "Batch List";
}

<!-- START BREADCRUMB -->
<ul class="breadcrumb push-down-0">
    <li><a href="#">Home</a></li>
    <li><a href="#">Course</a></li>
    <li><a href="#">Batch</a></li>
    @*<li class="active">Error 404</li>*@
</ul>
<!-- END BREADCRUMB -->
<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div>
        <div class="row">
            <div class="col-md-12">

                <form class="form-horizontal">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Batch List</h3>

                        </div>

                        <div class="panel-body">
                            <div class="row" style="padding-bottom:10px">
                                @*<button class="btn btn-info btn-rounded" data-toggle="modal" data-target="#modal_basic" ng-click="modules = null">Add New</button>*@
                                @Html.ActionLink("New Batch", "BatchCreate", "MasterDetails", null, new { data_modal = "", id = "btnCreate", @class = "btn btn-info btn-rounded" })
                            </div>

                            <div class="form-group">

                                <div class="col-md-3">
                                    <div class="input-group">
                                        <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                        @Html.DropDownList("CategoryId1",
                                                (IEnumerable<SelectListItem>)ViewBag.Category, "Select Category", new { @class = "form-control", @onchange = "FillCourse1()" })
                                    </div>

                                </div>

                                <div class="col-md-3">
                                    <div class="input-group">
                                        <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                        @Html.DropDownList("CourseId1",
                   new SelectList(Enumerable.Empty<SelectListItem>(), "CourseId", "CourseName"),
              " ", new { @class = "form-control"})
                                    </div>

                                </div>

                              

                                <div class="col-md-3">
                                    <div class="input-group">
                                        <input class="btn btn-primary" type="button" value="Search" onclick="Search()" />
                                    </div>

                                </div>
                            </div>
                            <div id="dvResult">
                                @{Html.RenderPartial("BatchListGet", Model);}

                            </div>
                            

                        </div>
                    </div>
                </form>

            </div>
        </div>


    </div>


</div>

<script>
    function FillCourse1() {
        var CategoryId = $('#CategoryId1').val();
        $.ajax({
            url: '/MasterDetails/FillCourse',
            type: "GET",
            dataType: "JSON",
            data: { CategoryId: CategoryId },
            success: function (Courses) {
                $("#CourseId1").html(""); // clear before appending new list
                $("#CourseId1").append(
                        $('<option></option>').val("").html("Select Course"));
                $.each(Courses, function (i, c) {
                    $("#CourseId1").append(
                        $('<option></option>').val(c.CourseId).html(c.CourseName));
                });
            }
        });
    }

    function Search() {
        var CourseId = $('#CourseId1').val();

        $("#dvResult").load('@(Url.Action("BatchListGet", "MasterDetails",null, Request.Url.Scheme))?CourseId=' + CourseId);
        //$('#customers2').DataTable();
    }
</script>

tsramol/Tsr.Web/Views/MasterDetails/CourseList.cshtml
@model IEnumerable<Tsr.Core.Models.MasterCourseListVM>

@{
    ViewBag.Title = "Course List";
}

<!-- START BREADCRUMB -->
<ul class="breadcrumb push-down-0">
    <li><a href="#">Home</a></li>
    <li><a href="#">Masters</a></li>
    <li><a href="#">Course</a></li>
    @*<li class="active">Error 404</li>*@
</ul>
<!-- END BREADCRUMB -->

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div>
        <div class="row">
            <div class="col-md-12">

                <form class="form-horizontal">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Course List</h3>

                        </div>

                        <div class="panel-body">
                            <div class="row" style="padding-bottom:10px">
                                @*<button class="btn btn-info btn-rounded" data-toggle="modal" data-target="#modal_basic" ng-click="modules = null">Add New</button>*@
                                @Html.ActionLink("New Course ", "CourseCreate", "MasterDetails", null, new { data_modal = "", id = "btnCreate", @class = "btn btn-info btn-rounded" })
                            </div>
                            <table id="customers2" class="table datatable">
                                <thead>
                                    <tr>
                                        <th>Course Name</th>
                                        <th>Category</th>
                                        <th>Duration</th>
                                        <th>Total Seats</th>
                                        @*<th>Coordinator</th>*@
                                        @*<th>Application Fee</th>*@
                                        @*<th>Min Balance</th>*@
                                        <th>Is Active</th>
                                        <th>Action</th>

                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.CourseName)
                                            </td>
                                            <td>@Html.DisplayFor(modelItem => item.CategoryName)</td>
                                            
                                            <td>
                                               @Html.DisplayFor(modelItem => item.Duration)
                                            </td>
                                            <td>@Html.DisplayFor(modelItem=>item.TotalSeat)</td>
                                            @*<td>@Html.DisplayFor(modelItem => item.Coordinator)</td>
                                            <td>@Html.DisplayFor(modelItem => item.ApplicationFee)</td>
                                            <td>@Html.DisplayFor(modelItem => item.MinBalance)</td>*@

                                            <td>
                                                @if (item.IsActive == true)
                                                {  <text> Yes</text>}
                                                else
                                                { <text> No</text> }
                                            </td>
                                            <td>
                                                @Html.ActionLink("Edit", "CourseEdit", new { id = item.CourseId }, new { data_modal = "" }) |
                                                @*@Html.ActionLink("Details", "CourseEdit", new { id = item.CourseId }, new { data_modal = "" }) |*@
                                                @Html.ActionLink("Documents", "CourseDocuments", new { id = item.CourseId }, new { data_modal = "" }) |
                                                @if (item.IsActive == true)
                                                {  @Html.ActionLink("Deactivate", "CourseDeactive", new { id = item.CourseId, flag = "D" }, new { onclick = "return confirm('Are you sure you wish to make Deactive?');" })}
                                                else
                                                {  @Html.ActionLink("Activate", "CourseDeactive", new { id = item.CourseId, flag = "A" }, new { onclick = "return confirm('Are you sure you wish to make Active?');" })}

                                            </td>
                                        </tr>
                                    }

                                </tbody>

                            </table>

                        </div>
                    </div>
                </form>

            </div>
        </div>


    </div>


</div>
<!-- END PAGE CONTENT WRAPPER -->


<script src="~/Scripts/js/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/Scripts/js/plugins/bootstrap/bootstrap-select.js"></script>
<script src="~/Scripts/ModalForm2.js"></script>

tsramol/Tsr.Web/Views/MasterDetails/DepartmentList.cshtml
@model IEnumerable<Tsr.Core.Models.MasterDetpartmentListVM>

@{
    ViewBag.Title = "Department List";
}

<!-- START BREADCRUMB -->
<ul class="breadcrumb push-down-0">
    <li><a href="#">Home</a></li>
    <li><a href="#">Masters</a></li>
    <li><a href="#">Department</a></li>
    @*<li class="active">Error 404</li>*@
</ul>
<!-- END BREADCRUMB -->
<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div>
        <div class="row">
            <div class="col-md-12">

                <form class="form-horizontal">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Department List</h3>

                        </div>

                        <div class="panel-body">
                            <div class="row" style="padding-bottom:10px">
                                @*<button class="btn btn-info btn-rounded" data-toggle="modal" data-target="#modal_basic" ng-click="modules = null">Add New</button>*@
                                @Html.ActionLink("New Department", "DepartmentCreate", "MasterDetails", null, new { data_modal = "", id = "btnCreate", @class = "btn btn-info btn-rounded" })
                            </div>
                            <table id="customers2" class="table datatable">
                                <thead>
                                    <tr>
                                        <th>Department Name</th>
                                        <th>Address</th>
                                        <th>Extension</th>
                                        <th>Phone</th>
                                        <th>Department Head</th>
                                        <th>Cell</th>

                                        <th>Is Active</th>
                                        <th>Action</th>

                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.DepartmentName)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Address)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Extension)
                                            </td>
                                            <td>@Html.DisplayFor(modelItem => item.Phone)</td>
                                            <td>@Html.DisplayFor(modelItem => item.DepartmentHead)</td>
                                            <td>@Html.DisplayFor(modelItem => item.Cellphone)</td>
                                            <td>
                                                @if (item.IsActive == true)
                                                {  <text> Yes</text>}
                                                else
                                                { <text> No</text> }
                                            </td>
                                            <td>
                                                @Html.ActionLink("Edit", "DepartmentEdit", new { id = item.DepartmentId }, new { data_modal = "" }) |
                                               
                                                @if (item.IsActive == true)
                                                {  @Html.ActionLink("Deactivate", "DepartmentDeactive", new { id = item.DepartmentId, flag = "D" }, new { onclick = "return confirm('Are you sure you wish to make Deactive?');" })}
                                                else
                                                {  @Html.ActionLink("Activate", "DepartmentDeactive", new { id = item.DepartmentId, flag = "A" }, new { onclick = "return confirm('Are you sure you wish to make Active?');" })}

                                            </td>
                                        </tr>
                                    }

                                </tbody>

                            </table>

                        </div>
                    </div>
                </form>

            </div>
        </div>


    </div>


</div>
<!-- END PAGE CONTENT WRAPPER -->
<!-- MODALS -->
<div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="defModalHead" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>

<script src="~/Scripts/js/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/Scripts/js/plugins/bootstrap/bootstrap-select.js"></script>
<script src="~/Scripts/ModalForm.js"></script>

tsramol/Tsr.Web/Views/MasterDetails/DesignationEdit.cshtml
@model Tsr.Core.Entities.Designation

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Add New Designation</h4>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model=>model.DesignationId)
    <div class="modal-body">

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.DesignationName, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.DesignationName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DesignationName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-8">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsActive, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal">Cancel</button>
        <input class="btn btn-primary" type="submit" value="Save" />
    </div>
}
<script type="text/javascript">
    $(document).ready(function () {
        $('#DesignationName').blur(function () {
            var DesignationName = $('#DesignationName').val();
            $.ajax({
                type: 'GET',
                url: '@Url.Action("IsDesignationNameExists")',
                dataType: 'JSON',
                data: { DesignationName: DesignationName },
                success: function (data) {
                    if (data.DesignationName != null) {
                        alert("Designation Name Already Exist")
                        $('#DesignationName').val('');
                        $('#DesignationName').focus();
                        return false;
                    }
                }
            });
        });
    })
</script>

tsramol/Tsr.Web/Views/MasterDetails/FeesPatternList.cshtml
@model IEnumerable<Tsr.Core.Entities.FeesPattern>

@{
    ViewBag.Title = "Fees Pattern List";
}

<!-- START BREADCRUMB -->
<ul class="breadcrumb push-down-0">
    <li><a href="#">Home</a></li>
    <li><a href="#">Masters</a></li>
    <li><a href="#">Fees Pattern</a></li>
    @*<li class="active">Error 404</li>*@
</ul>
<!-- END BREADCRUMB -->
<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div>
        <div class="row">
            <div class="col-md-12">

                <form class="form-horizontal">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Fees Pattern List</h3>

                        </div>

                        <div class="panel-body">
                            <div class="row" style="padding-bottom:10px">
                                @*<button class="btn btn-info btn-rounded" data-toggle="modal" data-target="#modal_basic" ng-click="modules = null">Add New</button>*@
                                @Html.ActionLink("New Fees Pattern", "FeesPatternCreate", "MasterDetails", null, new { data_modal = "", id = "btnCreate", @class = "btn btn-info btn-rounded" })
                            </div>
                            <table id="customers2" class="table datatable">
                                <thead>
                                    <tr>
                                        <th>Fees Pattern</th>
                                        <th>Is Active</th>
                                        <th>Action</th>

                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Name)
                                            </td>

                                            
                                            <td>
                                                @if (item.IsActive == true)
                                                {  <text> Yes</text>}
                                                else
                                                { <text> No</text> }
                                            </td>
                                            <td>
                                                @Html.ActionLink("Edit", "FeesPatternEdit", new { id = item.FeesPatternId }, new { data_modal = "" }) |
                                               
                                                @if (item.IsActive == true)
                                                {  @Html.ActionLink("Deactivate", "FeesPatternDeactive", new { id = item.FeesPatternId , flag = "D"}, new { onclick = "return confirm('Are you sure you wish to make Deactive?');" })}
                                                else
                                                {  @Html.ActionLink("Activate", "FeesPatternDeactive", new { id = item.FeesPatternId, flag = "A" }, new { onclick = "return confirm('Are you sure you wish to make Active?');" })}

                                            </td>
                                        </tr>
                                    }

                                </tbody>

                            </table>

                        </div>
                    </div>
                </form>

            </div>
        </div>


    </div>


</div>
<!-- END PAGE CONTENT WRAPPER -->
<!-- MODALS -->
<div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="defModalHead" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>

<script src="~/Scripts/js/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/Scripts/js/plugins/bootstrap/bootstrap-select.js"></script>
<script src="~/Scripts/ModalForm.js"></script>