tsramol/Tsr.Web/Controllers/AdmissionController.cs
using iTextSharp.text;
using iTextSharp.text.pdf;
using LinqToExcel;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Data.OleDb;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using Tsr.Core.Entities;
using Tsr.Core.Models;
using Tsr.Infra;
using Tsr.ToPdf;
using Tsr.Web.Common;

namespace Tsr.Web.Controllers
{
    public class AdmissionController : Controller
    {
        AppContext db = new AppContext();
        #region Common

        public JsonResult FillBatch(int? CourseId)
        {
            var C = db.Batches
                .Where(c => c.CourseId == CourseId && c.IsActive == true )
                .Select(x => new { BatchId = x.BatchId, Name = x.StartDate });

            var Batches = C.ToList().Select(x => new BatchDropdown { BatchId = x.BatchId, BatchCode = Convert.ToDateTime(x.Name).ToString("dd-MM-yyyy") });
            return Json(Batches, JsonRequestBehavior.AllowGet);
        }
        public JsonResult FillBatchForCet(int? CourseId)
        {
            var C = db.Batches
                .Where(c => c.CourseId == CourseId && c.IsActive == true )
                .Select(x => new { BatchId = x.BatchId, Name = x.StartDate });

            var Batches = C.ToList().Select(x => new BatchDropdown { BatchId = x.BatchId, BatchCode = Convert.ToDateTime(x.Name).ToString("dd-MM-yyyy") });
            return Json(Batches, JsonRequestBehavior.AllowGet);
        }

        public JsonResult FillCet(int? BatchId)
        {
            var C = db.CetMasters
             .Where(x => (x.BatchId == BatchId && x.IsActive == true))
             .Select(x => new { CetMasterId = x.CetMasterId, Name = x.CetDate });
            var Cet = C.ToList().Select(x => new CetDropdown { CetMasterId = x.CetMasterId, CetCode = Convert.ToDateTime(x.Name).ToString("dd-MM-yyyy") });
            return Json(Cet, JsonRequestBehavior.AllowGet);
        }


        #endregion
        public ActionResult Index()
        {

            return View();
        }

        #region CET
        [HttpGet]
        public ActionResult CETSchedule()
        {
            var a = from c in db.Courses
                    join cc in db.CourseCategories on c.CategoryId equals cc.CourseCategoryId
                    where (c.IsActive == true && cc.CetRequired == true)
                    select new { c.CourseId, c.CourseName };
            ViewBag.Courses = new SelectList(a.ToList(), "CourseId", "CourseName");

            ViewBag.Course = new SelectList(a.ToList(), "CourseId", "CourseName");

            var count = db.CetMasters.Count() + 1;
            var obj = new AddmissionCetCreateVM
            {
                CetCode = count.ToString().PadLeft(4, '0'),
                _AddmissionCetListVM = new List<AddmissionCetListVM>()
            };


            var Batches = new List<BatchDropdown>();

            ViewBag.Batches = new SelectList(Batches, "BatchId", "BatchCode");
            return View(obj);
        }

        [HttpGet]
        public ActionResult GetCetScheduleList(int? BatchId)
        {
            var vm = from cm in db.CetMasters
                     join c in db.Courses on cm.CourseId equals c.CourseId
                     join b in db.Batches on cm.BatchId equals b.BatchId
                     where (b.IsActive == true && b.OnlineBookingStatus == true && b.BatchId == BatchId)
                     select new AddmissionCetListVM
                     {
                         BatchCode = b.BatchCode,
                         CetCode = cm.CetCode,
                         CetDate = cm.CetDate,
                         CetId = cm.CetMasterId,
                         CetTime = cm.CetTime,
                         CourseCode = c.CourseCode,
                         CourseName = c.CourseName,
                         IsActive = cm.IsActive,
                         StartDate = b.StartDate,
                         Venue = cm.Venue
                     };
            if (vm.ToList().Count == 0)
            {
                var obj = new List<AddmissionCetListVM>();
                return PartialView("_CetScheduleList", obj.ToList());
            }
            else { return PartialView("_CetScheduleList", vm.ToList()); }



        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CETSchedule(AddmissionCetCreateVM obj)
        {
            if (ModelState.IsValid)
            {
                string filepathname = string.Empty;
                if (obj.CetId == 0 || obj.CetId == null)
                {
                    if (Request.Files.Count > 0)
                    {
                        var root = "/Uploads/CetFile/";

                        var files = Request.Files[0];
                        var ext = Path.GetExtension(files.FileName);
                        var fileName = obj.CetCode + ext;
                        var path = Server.MapPath(root + fileName);
                        files.SaveAs(path);
                        filepathname = root + fileName;

                    }
                    CetMaster cm = new CetMaster
                    {
                        BatchId = obj.BatchId,
                        CetCode = obj.CetCode,
                        CetDate = Convert.ToDateTime(obj.CetDates),
                        CetTime = obj.CetTime,
                        CourseId = obj.CourseId,
                        IsActive = obj.IsActive,
                        //StartDate = obj.StartDate,
                        FilePath = filepathname,
                        Venue = obj.Venue
                    };

                    db.CetMasters.Add(cm);
                    db.SaveChanges();
                }
                else
                {
                    if (Request.Files.Count > 0)
                    {
                        var root = "/Uploads/CetFile/";

                        var files = Request.Files[0];
                        var ext = Path.GetExtension(files.FileName);
                        var fileName = obj.CetCode + ext;
                        var path = Server.MapPath(root + fileName);
                        files.SaveAs(path);
                        filepathname = root + fileName;

                    }
                    CetMaster cm = new CetMaster
                    {
                        BatchId = obj.BatchId,
                        CetCode = obj.CetCode,
                        CetDate = Convert.ToDateTime(obj.CetDates),
                        CetTime = obj.CetTime,
                        CourseId = obj.CourseId,
                        IsActive = obj.IsActive,
                        CetMasterId = (int)obj.CetId,
                        FilePath = filepathname,
                        Venue = obj.Venue
                    };

                    db.Entry(cm).State = EntityState.Modified;
                    db.SaveChanges();

                }


            }

            return RedirectToAction("CETSchedule");

        }

        public ActionResult CetEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CetMaster fp = db.CetMasters.Find(id);
            if (fp == null)
            {
                return HttpNotFound();
            }
            AddmissionCetCreateVM vm = new AddmissionCetCreateVM
            {
                BatchId = fp.BatchId,
                CetCode = fp.CetCode,
                CetDates = Convert.ToDateTime(fp.CetDate).ToString("yyyy-MM-dd"),
                CetId = fp.CetMasterId,
                CetTime = fp.CetTime,
                CourseId = fp.CourseId,
                IsActive = fp.IsActive,
                Venue = fp.Venue,
                _AddmissionCetListVM = new List<AddmissionCetListVM>()


            };
            var a = from c in db.Courses
                    join cc in db.CourseCategories on c.CategoryId equals cc.CourseCategoryId
                    where (c.IsActive == true && cc.CetRequired == true)
                    select new { c.CourseId, c.CourseName };
            ViewBag.Course = new SelectList(a.ToList(), "CourseId", "CourseName");
            ViewBag.Courses = new SelectList(a.ToList(), "CourseId", "CourseName");
            var b = db.Batches.Where(x => x.CourseId == fp.CourseId)
                    .Select(x => new { BatchId = x.BatchId, Name = x.StartDate });

            var Batches = b.ToList().Select(x => new BatchDropdown { BatchId = x.BatchId, BatchCode = Convert.ToDateTime(x.Name).ToString("dd-MM-yyyy") });

            ViewBag.Batches = new SelectList(Batches, "BatchId", "BatchCode");
            return View("CETSchedule", vm);
        }

        #endregion

        #region Halltickets
        public ActionResult HallTickets()
        {
           

            var a = from c in db.Courses
                    join cc in db.CourseCategories on c.CategoryId equals cc.CourseCategoryId
                    where (c.IsActive == true && cc.CetRequired == true)
                    select new { c.CourseId, c.CourseName };
            ViewBag.Course = new SelectList(a.ToList(), "CourseId", "CourseName");
           
            var obj = new List<HallTicketListVM>();
            return View(obj);
        }
        public ActionResult GetApplicantForHalltickets(int? BatchId)
        {


            var list = from ap in db.Applications
                       join b in db.Batches on ap.BatchId equals b.BatchId
                       join cr in db.Courses on ap.CourseId equals cr.CourseId
                       join appl in db.Applied on ap.ApplicationId equals appl.ApplicationId
                       join ct in db.CetMarks on ap.ApplicationId equals ct.ApplicationId into cts

tsramol/Tsr.Web/Views/Admission/ApplicantsList.cshtml
@model IEnumerable<Tsr.Core.Models.ApplicationApplicantsList>

<table id="customers2" class="table datatable">
    <thead>
        <tr>

            <th>Application Code</th>
            <th>Name</th>
            
            <th>Email</th>
            <th>Cell</th>
            
            @*<th>Action</th>*@
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.ApplicationCode)</td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name) 
                </td>
                
                <td>@Html.DisplayFor(modelItem => item.Email)</td>
                <td>@Html.DisplayFor(modelItem => item.Cell)</td>
                
                
            </tr>
        }

    </tbody>

</table>

tsramol/Tsr.Web/Views/Admission/CetCreate.cshtml
@model Tsr.Core.Models.AddmissionCetCreateVM

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/js/plugins/bootstrap/bootstrap-select.js"></script>

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">New Cet Schedule </h4>
</div>
@using (Html.BeginForm("CetCreate", "Admission", FormMethod.Post, new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    <div class="modal-body">
        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            <div class="form-group">
                @Html.LabelFor(model => model.CetCode, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.CetCode, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CetCode, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CourseId, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-8">
                    @Html.DropDownListFor(model => model.CourseId,
                        (IEnumerable<SelectListItem>)ViewBag.Course, " ", new { @class = "form-control", @onchange = "FillBatchs()" })
                    @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BatchId, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-8">
                    @Html.DropDownListFor(model => model.BatchId, new SelectList(Enumerable.Empty<SelectListItem>(), "BatchId", "BatchCode"), " ", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.BatchId, "", new { @class = "text-danger" })
                </div>
            </div>

           

            <div class="form-group">
                @Html.LabelFor(model => model.CetDate, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-8">
                    @Html.TextBoxFor(model => model.CetDate, new { @class = "form-control", @type = "Date" })
                    @Html.ValidationMessageFor(model => model.CetDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.CetTime, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-8">
                    @Html.TextBoxFor(model => model.CetTime, new { @class = "form-control", @type = "time" })
                    @Html.ValidationMessageFor(model => model.CetTime, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Venue, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-8">
                    @Html.TextBoxFor(model => model.Venue, new { @class = "form-control"})
                    @Html.ValidationMessageFor(model => model.Venue, "", new { @class = "text-danger" })
                </div>
            </div>



            <div class="form-group">
                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.IsActive, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
          
            <div class="form-group">
                @Html.LabelFor(model => model.FileUpload, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-8">
                    @Html.TextBoxFor(m => m.FileUpload, new { type = "file", @onchange = "CheckValidation()" })
                    
                    @Html.ValidationMessageFor(m => m.FileUpload, string.Empty, new { id = "validationTxt", @class = "text-danger" })
                </div>
            </div>
                


            </div>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal">Cancel</button>
        <input class="btn btn-primary" type="submit" value="Save" id="btnSubmit" />
    </div>
}

<div class="modal fade" id="myModalSave" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Infromation Dialog</h4>
            </div>
            <div class="modal-body">
                <p id="txtMessage"></p>
            </div>
        </div>
    </div>
</div>


<script>
        $(document).ready(function () {
//Start of the document ready function
            $("#btnSubmit").click(function () {
                debugger;
                var frmData = new FormData();
                var filebase = $("#FileUpload").get(0);
                var files = filebase.files;
                frmData.append(files[0].name, files[0]);
                $.ajax({
                    url: '/Admission/CetCreate',
                    type: "POST",
                    contentType: false,
                    processData: false,
                    data: frmData,
                    success: function (data) {
                        $('#myModalSave').modal('show');
                        $('#txtMessage').html(data.message);
                        if (data.success) {
                            $('.modal-header').addClass('alert alert-success');
                        } else {
                            $('.modal-header').addClass('alert alert-info');
                        }
                    },
                    error: function (err) {
                        $('#myModalSave').modal('show');
                        $('.modal-header').addClass('alert alert-danger');
                        $('#txtMessage').html(err.statusText);
                    }
                });
            });

//End of the document ready function...
        });
</script>

tsramol/Tsr.Web/Views/Admission/HallTicketsNonPay.cshtml
@model IEnumerable<Tsr.Core.Models.HallTicketListVM>
@{
    ViewBag.Title = "HallTickets";
}

<!-- START BREADCRUMB -->
<ul class="breadcrumb push-down-0">
    <li><a href="#">Home</a></li>
    <li><a href="#">Admission</a></li>
    <li><a href="#">Hall Tickets Non Payment</a></li>
    @*<li class="active">Error 404</li>*@
</ul>
<!-- END BREADCRUMB -->
<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div>
        <div class="row">
            <div class="col-md-12">

                <form class="form-horizontal">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Hall Tickets Non Payments</h3>

                        </div>

                        <div class="panel-body">
                            <div class="row">

                                <div class="col-md-12">

                                    <div class="form-group">



                                        <div class="col-md-3">
                                            <div class="input-group">
                                                <span class="input-group-addon">Course</span>
                                                @Html.DropDownList("CourseId", (IEnumerable<SelectListItem>)ViewBag.Course, " ", new { @class = "form-control", @onchange = "FillBatch()" })
                                            </div>

                                        </div>

                                        <div class="col-md-3">
                                            <div class="input-group">
                                                <span class="input-group-addon">Batch</span>
                                                @Html.DropDownList("BatchId",
                   new SelectList(Enumerable.Empty<SelectListItem>(), "BatchId", "BatchCode"), " ", new { @class = "form-control", @onchange = "FillCet()" })
                                            </div>

                                        </div>

                                        @*<div class="col-md-3">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                @Html.DropDownList("CetMasterId",
                   new SelectList(Enumerable.Empty<SelectListItem>(), "CetMasterId", "CetCode"), " ", new { @class = "form-control" })
                                            </div>

                                        </div>*@

                                        <div class="col-md-6">
                                            <div class="input-group">
                                                <input class="btn btn-primary" type="button" value="Search" onclick="Search()" />
                                                @*&nbsp;&nbsp;&nbsp;&nbsp;<input class="btn btn-primary" type="button" value="Save All" onclick="location.href='@Url.Action("Export", "Admission")?id=' + document.getElementById('ApplicationId').value"   />*@
                                                &nbsp;&nbsp;<input type="button" class="btn btn-primary" value="Refresh Page" onClick="window.location.reload()">
                                                &nbsp;&nbsp; 
                                                <div class="btn-group">
                                                    <a href="#" data-toggle="dropdown" class="btn btn-success dropdown-toggle">Export <span class="caret"></span></a>
                                                    <ul class="dropdown-menu" role="menu" style="background-color: #57a9a8">
                                                        @*<li role="presentation" class="dropdown-header">Dropdown header</li>*@
                                                        <li><input class="btn btn-primary" type="button" value="View In Pdf" onclick="location.href='@Url.Action("ExportNonPay", "Admission")?id=' + document.getElementById('BatchId').value" /></li>
                                                        <li><input class="btn btn-primary" type="button" value="Excel List" onclick="location.href='@Url.Action("ExportNonPayEx", "Admission")?id=' + document.getElementById('BatchId').value" /></li>
                                                    </ul>
                                                </div>
                                            </div>

                                        </div>

                                    </div>


                                </div>


                            </div>
                            <div id="dvResult">
                                @{Html.RenderPartial("_HallticketApplicantNonPay", Model);}
                                <script src="~/Scripts/js/plugins/datatables/jquery.dataTables.min.js"></script>
                            </div>
                        </div>
                    </div>
                </form>

            </div>
        </div>


    </div>


</div>
<!-- END PAGE CONTENT WRAPPER -->
<script>

  function FillBatch() {
      var CourseId = $('#CourseId').val();
      $.ajax({
          url: '/Admission/FillBatch',
          type: "GET",
          dataType: "JSON",
          data: { CourseId: CourseId },
          success: function (Batches) {
              $("#BatchId").html(""); // clear before appending new list
              $("#BatchId").append(
                      $('<option></option>').val(0).html("Select Batch"));

              $.each(Batches, function (i, c) {
                  $("#BatchId").append(
                      $('<option></option>').val(c.BatchId).html(c.BatchCode));
              });
          }
      });
  }

  function FillCet() {
      var BatchId = $('#BatchId').val();
      $.ajax({
          url: '/Admission/FillCet',
          type: "GET",
          dataType: "JSON",
          data: { BatchId: BatchId },
          success: function (Cet) {
              $("#CetMasterId").html(""); // clear before appending new list
              $("#CetMasterId").append(
                      $('<option></option>').val(0).html("Select CetScedule"));

              $.each(Cet, function (i, c) {
                  $("#CetMasterId").append(
                      $('<option></option>').val(c.CetMasterId).html(c.CetCode));
              });
          }
      });
  }

  function Search() {
      var BatchId = $('#BatchId').val();

      $("#dvResult").load('@(Url.Action("GetApplicantForHallticketsNonPay", "Admission",null, Request.Url.Scheme))?BatchId=' + BatchId);
  }
</script>

tsramol/Tsr.Web/Views/Admission/Interview.cshtml
@model List<Tsr.Core.Models.AdmissionInterviewListVM>

@{
    ViewBag.Title = "Interview";
}

<!-- START BREADCRUMB -->
<ul class="breadcrumb push-down-0">
    <li><a href="#">Home</a></li>
    <li><a href="#">Admission</a></li>
    <li><a href="#">Interview</a></li>
    @*<li class="active">Error 404</li>*@
</ul>
<!-- END BREADCRUMB -->
<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div>
        <div class="row">
            <div class="col-md-12">

                <div class="form-horizontal">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Interview</h3>

                        </div>

                        <div class="panel-body">
                            <div class="row">

                                <div class="col-md-12">

                                    <div class="form-group">

                                        <div class="col-md-3">
                                            <div class="input-group">
                                                <span class="input-group-addon">Course</span>
                                                @Html.DropDownList("CourseId",
                                                (IEnumerable<SelectListItem>)ViewBag.Course, "Select Course", new { @class = "form-control", @onchange = "FillBatch()" })
                                            </div>

                                        </div>



                                        <div class="col-md-3">
                                            <div class="input-group">
                                                <span class="input-group-addon">Batch</span>
                                                @Html.DropDownList("BatchId",
                   new SelectList(Enumerable.Empty<SelectListItem>(), "BatchId", "BatchCode"),
              " ", new { @class = "form-control"})
                                            </div>

                                        </div>

                                        <div class="col-md-3">
                                            <div class="input-group">
                                                <input class="btn btn-primary" type="button" value="Search" onclick="Search()" />
                                                &nbsp;&nbsp; <input type="button" class="btn btn-primary" value="Refresh Page" onClick="window.location.reload()">
                                                &nbsp;
                                                <div class="btn-group">
                                                    <a href="#" data-toggle="dropdown" class="btn btn-success dropdown-toggle">Export <span class="caret"></span></a>
                                                    <ul class="dropdown-menu" role="menu" style="background-color: #57a9a8">
                                                        @*<li role="presentation" class="dropdown-header">Dropdown header</li>*@
                                                        @*<li><input class="btn btn-primary" type="button" value="View In Pdf" onclick="location.href='@Url.Action("Export", "Admission")?id=' + document.getElementById('BatchId').value" /></li>*@
                                                        <li><input class="btn btn-primary" type="button" value="Excel List" onclick="location.href='@Url.Action("InterviewEx", "Admission")?BatchId=' + document.getElementById('BatchId').value" /></li>
                                                    </ul>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                    <div class="form-group">
                                       
                                    </div>



                                </div>


                            </div>
                            <div id="dvResult">
                                @{Html.RenderPartial("InterviewList", Model);}

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>


    </div>


</div>
<!-- END PAGE CONTENT WRAPPER -->
<script>
    function FillBatch() {
        //debugger;
        var CourseId = $('#CourseId').val();
        $.ajax({
            url: '/Admission/FillBatch',
            type: "GET",
            dataType: "JSON",
            data: { CourseId: CourseId },
            success: function (Batches) {
                $("#BatchId").html(""); // clear before appending new list
                $("#BatchId").append(
                        $('<option></option>').val(0).html("Select Batch"));
                $.each(Batches, function (i, c) {
                    $("#BatchId").append(
                        $('<option></option>').val(c.BatchId).html(c.BatchCode));
                });
            }
        });
    }

    
   function Search() {
      var BatchId = $('#BatchId').val();
      
      $("#dvResult").load('@(Url.Action("GetListForInterview", "Admission",null, Request.Url.Scheme))?BatchId=' + BatchId );
      //$('#customers2').DataTable();
  }
</script>

tsramol/Tsr.Web/Views/Admission/InterviewList.cshtml
@model List<Tsr.Core.Models.AdmissionInterviewListVM>
@using (Html.BeginForm("Interview", "Admission", FormMethod.Post))
{
<table id="customers2" class="table ">
    <thead>
        <tr>
            
            <th>Application Code</th>
            <th>Name</th>

            <th>Email</th>
            <th>Cell</th>
            <th>Select</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Count(); i++)
        {
            <tr>
                @Html.Hidden("obj[" + @i + "].ApplicationId", Model[i].ApplicationId)
                <td>
                    @Html.Hidden("obj[" + @i + "].ApplicationCode", Model[i].ApplicationCode)
                    @Model[i].ApplicationCode
                </td>
                <td>
                    @Html.Hidden("obj[" + @i + "].Name", Model[i].Name)
                    @Model[i].Name
                </td>
                <td>
                    @Html.Hidden("obj[" + @i + "].Email", Model[i].Email)
                    @Model[i].Email
                </td>
                <td>
                    @Html.Hidden("obj[" + @i + "].Cell", Model[i].Cell)
                    @Model[i].Cell
                </td>
                <td>
                    @Html.CheckBox("obj[" + @i + "].Select", Model[i].Select)
                </td>

            </tr>
        }

        

    </tbody>

</table>
    if (ViewBag.Flag == "1")
    {
        <div class="col-md-3">
            <div class="input-group">
                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                @Html.DropDownList("MedicalMasterId", (IEnumerable<SelectListItem>)ViewBag.MedicalMaster, "Select Medical", new { @class = "form-control" })
            </div>

        </div>

        <div class="col-md-3">
            <div class="input-group">
                <input class="btn btn-primary" type="submit" value="Mark for Medical" />

            </div>

        </div>

    }
}