tsramol/Tsr.Web/Controllers/ManageUsersController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Tsr.Core.Entities;
using Tsr.Core.Models;
using Tsr.Infra;
using Tsr.Web.Models;

namespace Tsr.Web.Controllers
{
    public class ManageUsersController : Controller
    {
        ApplicationDbContext db;
        AppContext ndb;
        private ApplicationUserManager _userManager;

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

#region Users
        public ActionResult UserLists()
        {
            db = new ApplicationDbContext();

            var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>
               (db));

            var users = db.Users.ToList();

            var viewModels = new List<UserlistViewModel>();

            foreach (var user in users)
            {
                var s = UserManager.GetRoles(user.Id);
                string rolename = string.Empty;
                try { rolename = s[0].ToString(); }
                catch (Exception) { rolename = "None"; }

                viewModels.Add(new UserlistViewModel { Id = user.Id, Name = user.UserName, Role = rolename });
            }
            return View(viewModels);
        }

        public ActionResult CreateUser()
        {
            ndb = new AppContext();
            db = new ApplicationDbContext();
            var emp = ndb.Employees
                        .Where(x => x.IsActive == true)
                        .ToList()
                        .Select(x => new { EmployeeId = x.EmployeeId, EmployeeName = string.Format("{0} {1}", x.EmployeeCode, x.FirstName) });
            ViewBag.Employees = new SelectList(emp, "EmployeeId", "EmployeeName");
            //ViewBag.Roles = new SelectList(db.Roles, "RoleId", "Role");
            ViewBag.Roles = new SelectList(db.Roles.ToList(), "Name", "Name");

            return PartialView("_CreateUser");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateUser(CreateUserVM model)
        {
            ndb = new AppContext();
            db = new ApplicationDbContext();
            
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = model.UserName, EmployeeId = model.EmployeeId, Email = model.Email };
                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    // await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                    await this.UserManager.AddToRoleAsync(user.Id, model.RoleId);
                    // For more information on how to enable account confirmation and password reset please visit http://go.microsoft.com/fwlink/?LinkID=320771
                    // Send an email with this link
                    // string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                    // var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                    // await UserManager.SendEmailAsync(user.Id, "Confirm your account", "Please confirm your account by clicking <a href=\"" + callbackUrl + "\">here</a>");

                    return Json(new { success = true });
                }
                AddErrors(result);
            }

            var emp = ndb.Employees
                        .Where(x => x.IsActive == true)
                        .ToList()
                        .Select(x => new { EmployeeId = x.EmployeeId, EmployeeName = string.Format("{0} {1}", x.EmployeeCode, x.FirstName) });
            ViewBag.Employees = new SelectList(emp, "EmployeeId", "EmployeeName");
            ViewBag.Roles = new SelectList(db.Roles.ToList(), "Name", "Name");
            return PartialView("_CreateUser", model);
        }

        #endregion

        #region Roles
        public ActionResult RolesList()
        {
            db = new ApplicationDbContext();
            var roles = db.Roles.ToList();
            return View(roles);
        }

        public ActionResult CreateRole()
        {
            return PartialView("_RoleCreate");
        }
        [HttpPost]
        public ActionResult CreateRole(CreateRoleVM vm)
        {
            if (ModelState.IsValid)
            {
                db = new ApplicationDbContext();
                var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));
                if (!roleManager.RoleExists(vm.Roles))
                {
                    var role = new Microsoft.AspNet.Identity.EntityFramework.IdentityRole();
                    role.Name = vm.Roles;
                    roleManager.Create(role);
                    return Json(new { success = true });
                }
                else
                {
                    ModelState.AddModelError("Role Already exist", "Role Already exist");
                    return PartialView("_RoleCreate", vm);
                }
            }
            
            return PartialView("_RoleCreate",vm);
        }

        public ActionResult RoleMenu(string Id)
        {
            ndb = new AppContext(); 
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var obj = (from um in ndb.UserMenus
                       join sm in ndb.SubMenus on um.SubMenuId equals sm.Id
                       //join mm in ndb.MainMenus on um.MainMenuId equals mm.Id
                       where (um.RoleId == Id)
                       select sm.Id).ToArray();

            //var docs = ndb.SubMenus.Where(x => x.IsActive == true).ToList();
            var docs = (from sm in ndb.SubMenus
                        join mm in ndb.MainMenus on sm.MainMenuId equals mm.Id
                        where (sm.IsActive == true)
                        select new { Id = sm.Id, Name = mm.Name + " -> " + sm.Name }).ToList();
            ViewBag.SubMenu = new MultiSelectList(docs, "Id", "Name", obj);

            ViewBag.RoleId = Id;
            return PartialView("RoleMenu");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RoleMenu(IEnumerable<int> SubMenuListId, string id)
        {
            ndb = new AppContext();
            //int CourseId = Convert.ToInt32(id);

            ndb.UserMenus.RemoveRange(ndb.UserMenus.Where(x => x.RoleId == id));
            await ndb.SaveChangesAsync();

            foreach (var item in SubMenuListId)
            {
                var obj = new UserMenu { SubMenuId = item, RoleId = id, MainMenuId = ndb.SubMenus.Find(item).MainMenuId };
                ndb.UserMenus.Add(obj);
                await ndb.SaveChangesAsync();
            }
            //return PartialView("CourseDocuments");
            return Json(new { success = true });
        }

        #endregion

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }
    }
}

tsramol/Tsr.Web/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tsr.Infra;
using Tsr.Core.Models;
using System.IO;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Tsr.ToPdf;
using Tsr.Web.Common;
using Aspose.Email.Clients.Exchange.WebService;
using Aspose.Email;
using Aspose.Email.Clients.Exchange;
using System.Threading.Tasks;
using System.Web.UI.WebControls;
using System.Web.UI;

namespace Tsr.Web.Controllers
{
    public class ReportController : Controller
    {
        // GET: Report
        AppContext db = new AppContext();

        #region trainedReport
        public ActionResult TrainedCandidates()
        {
            var obj = new List<ReportDatewiseTrainedVM>();
            return View(obj);
        }
        public ActionResult GetListTrainedCandidates(DateTime? StartDate, DateTime? EndDate)
        {
            if (StartDate != null && EndDate != null)
            {
                int pcnt = 0, rcnt = 0;
                var list = (from mt in db.Applied.AsEnumerable()
                           join ap in db.Applications on mt.ApplicationId equals ap.ApplicationId
                           join b in db.Batches on mt.BatchId equals b.BatchId
                           join c in db.Courses on mt.CourseId equals c.CourseId
                           //join sfd in db.StudentFeeDetails on ap.ApplicationId equals sfd.ApplicationId
                           join cf in db.CourseFees on c.CourseId equals cf.CourseId
                           where (b.StartDate >= StartDate && b.StartDate <= EndDate && mt.AdmissionStatus == true)
                           orderby (c.CategoryId)
                           select new
                           {
                               CourseId = c.CourseId,
                               //CatetoryId = c.CategoryId,
                               CourseName = c.CourseName,
                               IsPackage = ap.IsPackage,
                               //PackageAmt = sfd.FeePaid
                               //PackageAmt = (Convert.ToBoolean(ap.IsPackage)) ? cf.PackageFee : 0,
                               //RegularAmt = (Convert.ToBoolean(!ap.IsPackage)) ? cf.ActualFee : 0,
                               PackageAmt = cf.PackageFee + ((decimal)cf.PackageFee / 100 * (decimal)cf.GstPercentage),
                               RegularAmt = cf.ActualFee + ((decimal)cf.ActualFee / 100 * (decimal)cf.GstPercentage),
                               tax = cf.GstPercentage,
                              pcnt = (Convert.ToBoolean(ap.IsPackage)) ? ++pcnt : pcnt,
                               rcnt = (Convert.ToBoolean(!ap.IsPackage)) ? ++rcnt : rcnt
                           }).ToList();


                var list2 = list.GroupBy(l => l.CourseId)
                            .Select(x => new ReportDatewiseTrainedVM
                            {
                                CourseName = x.First().CourseName,
                                IsPackage = x.First().IsPackage,
                                //PackageAmt = Convert.ToDecimal(x.Sum(p => p.PackageAmt)),
                                // RegularAmt = Convert.ToDecimal(x.Sum(p=>p.RegularAmt)),
                                PackageAmt = Convert.ToDecimal(x.First().PackageAmt), 
                                RegularAmt = Convert.ToDecimal(x.First().RegularAmt),
                                //tax = Convert.ToDecimal( x.First().tax),
                                pcnt = x.Count(p=>p.IsPackage == true),
                                rcnt = x.Count(p => p.IsPackage != true)
                            }
                            ).ToList();

                return PartialView("TrainedCandidatesList", list2.ToList());
            }
           
            var obj = new List<ReportDatewiseTrainedVM>();
            return PartialView("TrainedCandidatesList",obj);
        }
        public ActionResult ExportToExcelTrainedCandidates(DateTime? StartDate, DateTime? EndDate)
        {
            var gv = new GridView();

            int pcnt = 0, rcnt = 0;
            var list = from mt in db.Applied.AsEnumerable()
                       join ap in db.Applications on mt.ApplicationId equals ap.ApplicationId
                       join b in db.Batches on mt.BatchId equals b.BatchId
                       join c in db.Courses on mt.CourseId equals c.CourseId
                       //join sfd in db.StudentFeeDetails on ap.ApplicationId equals sfd.ApplicationId
                       join cf in db.CourseFees on c.CourseId equals cf.CourseId
                       where (b.StartDate >= StartDate && b.StartDate <= EndDate && mt.AdmissionStatus == true)
                       orderby (c.CategoryId)
                       select new
                       {
                           CourseId = c.CourseId,
                           //CatetoryId = c.CategoryId,
                           CourseName = c.CourseName,
                           IsPackage = ap.IsPackage,
                           
                           PackageAmt = cf.PackageFee + ((decimal)cf.PackageFee / 100 * (decimal)cf.GstPercentage),
                           RegularAmt = cf.ActualFee + ((decimal)cf.ActualFee / 100 * (decimal)cf.GstPercentage),
                           tax = cf.GstPercentage,
                           pcnt = (ap.IsPackage.ToString()=="true") ? ++pcnt : pcnt,
                           rcnt = (ap.IsPackage.ToString()!="true") ? ++rcnt : rcnt
                       };

            int cnt = 1;
            var list2 = list.GroupBy(l => l.CourseId)
                        .Select(x => new 
                        {
                            SrNo = cnt++,
                            CourseName = x.First().CourseName,
                           
                                PackageAmount = x.First().PackageAmt,
                            PackageCandidates = x.Count(p => p.IsPackage == true),
                            RegularAmount = x.First().RegularAmt,
                            RegularCandidates = x.Count(p => p.IsPackage != true),
                            TotalCandidates = x.Count(p => p.IsPackage == true) + x.Count(p => p.IsPackage != true),
                            TotalAmount = (x.First().PackageAmt * x.Count(p => p.IsPackage == true)) + (x.First().RegularAmt * x.Count(p => p.IsPackage != true))
                        }
                        ).ToList();

            gv.DataSource = list2.ToList();
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=ConfirmAdmissions.xls");
            Response.ContentType = "application/ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View("Index");
        }
        public ActionResult GetListTrainedCandidates2(DateTime? StartDate, DateTime? EndDate)
        {
            if (StartDate != null && EndDate != null)
            {
                int pcnt = 0, rcnt = 0;
                var list = from mt in db.Applied.AsEnumerable()
                           join ap in db.Applications on mt.ApplicationId equals ap.ApplicationId
                           join b in db.Batches on mt.BatchId equals b.BatchId
                           join c in db.Courses on mt.CourseId equals c.CourseId
                           join sfd in db.StudentFeeDetails on ap.ApplicationId equals sfd.ApplicationId
                           join cf in db.CourseFees on c.CourseId equals cf.CourseId
                           where (b.StartDate >= StartDate && b.EndDate <= EndDate && mt.AdmissionStatus == true)
                           orderby (c.CategoryId)
                           select new
                           {
                               CourseId = c.CourseId,
                               //CatetoryId = c.CategoryId,
                               CourseName = c.CourseName,
                               IsPackage = ap.IsPackage,
                               //PackageAmt = sfd.FeePaid
                               PackageAmt = (Convert.ToBoolean(ap.IsPackage)) ? cf.PackageFee : 0,
                               RegularAmt = (Convert.ToBoolean(!ap.IsPackage)) ? sfd.FeePaid : 0,
                               pcnt = (Convert.ToBoolean(ap.IsPackage)) ? ++pcnt : pcnt,
                               rcnt = (Convert.ToBoolean(!ap.IsPackage)) ? ++rcnt : rcnt
                           };


                var list2 = list.GroupBy(l => l.CourseId)
                            .Select(x => new ReportDatewiseTrainedVM
                            {
                                CourseName = x.First().CourseName,
                                IsPackage = x.First().IsPackage,
                                PackageAmt = Convert.ToDecimal(x.Sum(p => p.PackageAmt)),
                                RegularAmt = Convert.ToDecimal(x.Sum(p => p.RegularAmt)),
                                pcnt = x.Count(p => p.IsPackage == true),
                                rcnt = x.Count(p => p.IsPackage == false)
                            }
                            ).ToList();

                return PartialView("TrainedCandidatesList", list2.ToList());
            }

            var obj = new List<ReportDatewiseTrainedVM>();
            return PartialView("TrainedCandidatesList", obj);
        }
        #endregion
        public ActionResult test()
        {
            EmailModel em = new EmailModel
            {
                //From = ConfigurationManager.AppSettings["admsmail"],
                //FromPass = ConfigurationManager.AppSettings["admsps"],

tsramol/Tsr.Web/Views/Shared/_SidebarAdmin.cshtml
<div class="page-sidebar">
    <!-- START X-NAVIGATION -->
    <ul class="x-navigation">
        <li class="xn-logo">
            <a href="index.html">TSRahaman</a>
            <a href="#" class="x-navigation-control"></a>
        </li>
        <li class="xn-profile">
            <a href="#" class="profile-mini">
                <img src="~/Img/avatar.png" alt="TSRahaman" />
            </a>
            <div class="profile">
                <div class="profile-image">
                    <img src="~/Img/avatar.png" alt="TSRahaman" />
                </div>
                <div class="profile-data">
                    <div class="profile-data-name">Admin</div>
                    <div class="profile-data-title">Training Ship Rahaman</div>
                </div>
                <div class="profile-controls">
                    <a href="pages-profile.html" class="profile-control-left"><span class="fa fa-info"></span></a>
                    <a href="pages-messages.html" class="profile-control-right"><span class="fa fa-envelope"></span></a>
                </div>
            </div>
        </li>

        <li class="xn-openable ">
            <a href="#"><span class="fa fa-files-o"></span> <span class="xn-text">Users</span></a>
            <ul>
                <li><a href="@Url.Action("UserLists", "ManageUsers")"><span class="fa fa-indent"></span> Users Lists</a></li>

            </ul>
        </li>

        <li class="xn-openable ">
            <a href="#"><span class="fa fa-files-o"></span> <span class="xn-text">Master Details</span></a>
            <ul>
                <li><a href="@Url.Action("OrganisationList", "MasterDetails")"><span class="fa fa-indent"></span> Organisation</a></li>
                <li><a href="@Url.Action("CourseCategoryList", "MasterDetails")"><span class="fa fa-circle-o"></span> Course Category</a></li>

                <li><a href="@Url.Action("EmployeeList", "MasterDetails")"><span class="fa fa-dot-circle-o"></span> Employee</a></li>
                <li><a href="@Url.Action("DocumentList", "MasterDetails")"><span class="fa fa-dot-circle-o"></span> Documents</a></li>
                <li><a href="@Url.Action("DepartmentList", "MasterDetails")"><span class="fa fa-dot-circle-o"></span> Departments</a></li>
                <li><a href="@Url.Action("DesignationList", "MasterDetails")"><span class="fa fa-dot-circle-o"></span> Designations</a></li>
                <li><a href="@Url.Action("FeesPatternList", "MasterDetails")"><span class="fa fa-dot-circle-o"></span> Fees Pattern</a></li>

                @*<li><a href="@Url.Action("InterviewList", "MasterDetails")"><span class="fa fa-dot-circle-o"></span> Interview</a></li>
                    <li><a href="@Url.Action("MedicalList", "MasterDetails")"><span class="fa fa-dot-circle-o"></span> Medical</a></li>*@
                <li><a href="@Url.Action("CertificateFormatList", "MasterDetails")"><span class="fa fa-circle-o"></span>Certificate Format</a></li>


                @*<li class="xn-openable">
                        <a href="#"><span class="fa fa-clock-o"></span> Address</a>
                        <ul>
                            <li> <a href="@Url.Action("CountryList", "MasterDetails")"><span class="fa fa-image"></span> Countries</a></li>
                            <li> <a href="@Url.Action("StateList","MasterDetails")"><span class="fa fa-image"></span> States</a></li>
                            <li> <a href="@Url.Action("DistrictList","MasterDetails")"><span class="fa fa-image"></span> District</a></li>
                        </ul>
                    </li>*@

                @*<li>@Html.ActionLink("Organisation", "OrganisationList", "MasterDetails") <span class="fa fa-image"></span> </li>*@

            </ul>
        </li>

        <li class="xn-openable ">
            <a href="#"><span class="fa fa-files-o"></span> <span class="xn-text">Course</span></a>
            <ul>

                <li><a href="@Url.Action("CourseList", "MasterDetails")"><span class="fa fa-circle-o"></span> Course</a></li>
                <li><a href="@Url.Action("PackageList", "MasterDetails")"><span class="fa fa-dot-circle-o"></span> Package</a></li>
                <li><a href="@Url.Action("CourseFeeList", "MasterDetails")"><span class="fa fa-dot-circle-o"></span> Course Fee</a></li>
                <li><a href="@Url.Action("BatchList", "MasterDetails")"><span class="fa fa-dot-circle-o"></span> Batch</a></li>

            </ul>
        </li>

        <li class="xn-openable ">
            <a href="#"><span class="fa fa-files-o"></span> <span class="xn-text">Fees</span></a>
            <ul>

                @*<li><a href="@Url.Action("FeeReciept", "Fees")"><span class="fa fa-circle-o"></span> Reciepts</a></li>*@
                <li><a href="@Url.Action("Scrutinee", "Fees")"><span class="fa fa-dot-circle-o"></span>Scrutinee Payments</a></li>
                <li><a href="@Url.Action("coursepayments", "Fees")"><span class="fa fa-dot-circle-o"></span> Course Payments</a></li>
                <li><a href="@Url.Action("checkPaymentStatus", "Fees")"><span class="fa fa-dot-circle-o"></span> Online Payment Status</a></li>
                <li><a href="@Url.Action("PaymentDetails", "Report")"><span class="fa fa-circle-o"></span>Payment Details</a></li>
                <li><a href="@Url.Action("TrainedCandidates", "Report")"><span class="fa fa-circle-o"></span>Candidates Trained</a></li>
                <li><a href="@Url.Action("EditFeesReciept", "Fees")"><span class="fa fa-circle-o"></span>Edit Reciept Amount</a></li>

            </ul>
        </li>

        <li class="xn-openable ">
            <a href="#"><span class="fa fa-files-o"></span> <span class="xn-text">Application</span></a>
            <ul>

                <li><a href="@Url.Action("Index", "Application")"><span class="fa fa-circle-o"></span> Book Course</a></li>
                <li><a href="@Url.Action("OfflineApplication", "Application")"><span class="fa fa-circle-o"></span> Book Course Offline</a></li>
                <li><a href="@Url.Action("ViewApplicants", "Application")"><span class="fa fa-dot-circle-o"></span>Applicants</a></li>
                <li><a href="@Url.Action("ApplicationForm", "Report")"><span class="fa fa-circle-o"></span>Application Form</a></li>

                @*<li><a href="@Url.Action("NonCetApplication", "Application")"><span class="fa fa-dot-circle-o"></span> Non-CET Dev</a></li>
                    <li><a href="@Url.Action("CetApplication", "Application")"><span class="fa fa-dot-circle-o"></span> CET Dev</a></li>*@


            </ul>
        </li>

        <li class="xn-openable ">
            <a href="#"><span class="fa fa-files-o"></span> <span class="xn-text">Admission</span></a>
            <ul>

                <li><a href="@Url.Action("CetSchedule", "Admission")"><span class="fa fa-circle-o"></span> Cet Schedule</a></li>
                <li><a href="@Url.Action("InterviewSchedule", "Admission")"><span class="fa fa-dot-circle-o"></span> Interview Schedule</a></li>
                <li><a href="@Url.Action("MedicalSchedule", "Admission")"><span class="fa fa-dot-circle-o"></span> Medical Schedule</a></li>
                <li><a href="@Url.Action("Scrutinee", "Admission")"><span class="fa fa-circle-o"></span> Scrutinee</a></li>
                <li><a href="@Url.Action("ViewApplied", "Admission")"><span class="fa fa-dot-circle-o"></span>Applied Students</a></li>
                <li><a href="@Url.Action("HallTickets", "Admission")"><span class="fa fa-dot-circle-o"></span> Hall Tickets</a></li>
                <li><a href="@Url.Action("HallTicketsNonPay", "Admission")"><span class="fa fa-dot-circle-o"></span> HallTickets Non Pay</a></li>
                <li><a href="@Url.Action("EntranceMarksEntry", "Admission")"><span class="fa fa-dot-circle-o"></span> Entrance Marks Entry</a></li>
                <li><a href="@Url.Action("TopStudents", "Admission")"><span class="fa fa-dot-circle-o"></span> Top Students</a></li>
                <li><a href="@Url.Action("Interview", "Admission")"><span class="fa fa-dot-circle-o"></span> Interview</a></li>
                <li><a href="@Url.Action("MedicalTest", "Admission")"><span class="fa fa-dot-circle-o"></span> Medical</a></li>
                <li><a href="@Url.Action("ConfirmAdmissions", "Admission")"><span class="fa fa-dot-circle-o"></span> Confirmed Students</a></li>
                <li><a href="@Url.Action("CompanyReservation", "Admission")"><span class="fa fa-dot-circle-o"></span> Company Reservation</a></li>
                <li><a href="@Url.Action("DiscontinueStudent", "Admission")"><span class="fa fa-dot-circle-o"></span> Discontinue Student</a></li>
                <li><a href="@Url.Action("UploadExcelCertNumber", "Certification")"><span class="fa fa-dot-circle-o"></span> Upload Certificate No</a></li>
            </ul>
        </li>
        

    
    <li class="xn-openable ">
        <a href="#"><span class="fa fa-files-o"></span> <span class="xn-text">Certification</span></a>
        <ul>

            <li><a href="@Url.Action("DesignCertificate", "Certification")"><span class="fa fa-circle-o"></span>Design Certificate</a></li>
            <li><a href="@Url.Action("PrincipalSignImage", "Certification")"><span class="fa fa-circle-o"></span>Principal Sign</a></li>
            <li><a href="@Url.Action("CheckList", "Certification")"><span class="fa fa-circle-o"></span>Check List</a></li>
            <li><a href="@Url.Action("CheckListEdit", "Certification")"><span class="fa fa-circle-o"></span>Check List Edit</a></li>
            <li><a href="@Url.Action("ViewResultSheet", "Certification")"><span class="fa fa-circle-o"></span>View Result Sheet</a></li>
            <li><a href="@Url.Action("Certificate", "Certification")"><span class="fa fa-circle-o"></span>Certificate</a></li>
            <li><a href="@Url.Action("NewCertificateDG", "Certification")"><span class="fa fa-dot-circle-o"></span> New Certificate</a></li>
        </ul>
    </li>

    </ul>
    <!-- END X-NAVIGATION -->
</div>

tsramol/Tsr.Web/Views/Shared/_SidebarFees.cshtml
<div class="page-sidebar">
    <!-- START X-NAVIGATION -->
    <ul class="x-navigation">
        <li class="xn-logo">
            <a href="index.html">TSRahaman</a>
            <a href="#" class="x-navigation-control"></a>
        </li>
        <li class="xn-profile">
            <a href="#" class="profile-mini">
                <img src="~/Img/avatar.png" alt="TSRahaman" />
            </a>
            <div class="profile">
                <div class="profile-image">
                    <img src="~/Img/avatar.png" alt="TSRahaman" />
                </div>
                <div class="profile-data">
                    <div class="profile-data-name">Fees</div>
                    <div class="profile-data-title">Training Ship Rahaman</div>
                </div>
                <div class="profile-controls">
                    <a href="pages-profile.html" class="profile-control-left"><span class="fa fa-info"></span></a>
                    <a href="pages-messages.html" class="profile-control-right"><span class="fa fa-envelope"></span></a>
                </div>
            </div>
        </li>


        <li class="xn-openable ">
            <a href="#"><span class="fa fa-files-o"></span> <span class="xn-text">Fees</span></a>
            <ul>

                @*<li><a href="@Url.Action("FeeReciept", "Fees")"><span class="fa fa-circle-o"></span> Reciepts</a></li>*@
                <li><a href="@Url.Action("Scrutinee", "Fees")"><span class="fa fa-dot-circle-o"></span>Scrutinee Payments</a></li>
                <li><a href="@Url.Action("coursepayments", "Fees")"><span class="fa fa-dot-circle-o"></span> Course Payments</a></li>
                <li><a href="@Url.Action("checkPaymentStatus", "Fees")"><span class="fa fa-dot-circle-o"></span> Online Payment Status</a></li>
                <li><a href="@Url.Action("PaymentDetails", "Report")"><span class="fa fa-circle-o"></span>Payment Details</a></li>
                <li><a href="@Url.Action("EditFeesReciept", "Fees")"><span class="fa fa-circle-o"></span>Edit Reciept Amount</a></li>
            </ul>
        </li>

        

    </ul>
    <!-- END X-NAVIGATION -->
</div>